version: '3.8'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.web
    container_name: clinic_web
    volumes:
      - ./app:/var/www/html
    ports:
      - "8030:80"
    depends_on:
      - db
    environment:
      PHP_ENV: development

  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.db
    container_name: app_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  db_data:
