version: '3'
services:
  app:
    image: ${NOME_IMAGEM}
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_DB=${NOME_BANCO_DADOS}
      - POSTGRES_USER=${USUARIO_BANCO_DADOS}
      - POSTGRES_PASSWORD=${SENHA_BANCO_DADOS}
    volumes:
      - ./zeus:/var/www/html
    depends_on:
      - db
    networks:
      - zeus_network

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${NOME_BANCO_DADOS}
      - POSTGRES_USER=${USUARIO_BANCO_DADOS}
      - POSTGRES_PASSWORD=${SENHA_BANCO_DADOS}
    ports:
      - "5432:5432"
    networks:
      - zeus_network

networks:
  zeus_network: