FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libonig-dev \
    zip \
    unzip \
    git \
    vim \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pgsql pdo pdo_pgsql mbstring zip

COPY php.ini /usr/local/etc/php/conf.d/custom.ini

RUN a2enmod rewrite

WORKDIR /var/www/html

EXPOSE 80
